
require 'jkr/array'
require 'jkr/numeric'
require 'jkr/env'
require 'jkr/error'
require 'jkr/plan'
require 'jkr/trial'
require 'jkr/analysis'
require 'jkr/cpufreq'
require 'jkr/cpu_usage'
require 'jkr/sysinfo'
require 'jkr/analytics'
require 'jkr/plot'
require 'jkr/stat'
require 'jkr/userutils'
require 'jkr/cli'
